version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

  wordpress:
    depends_on:
      - db
    image: conetix/wordpress-with-wp-cli
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/wp-content
      - ./volumes/uploads:/var/www/html/wp-content/uploads
      - ./scripts:/opt/scripts
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      ENV: local
    build:
      context: ./
      dockerfile: docker/wordpress/Dockerfile

volumes:
    db_data:
    legacy_files:
